import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "My Playground",
  description: "Generated by create next app",
};

export default function PlaygroundLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return <section className="m-12 border grow shadow-md">{children}</section>;
}
